model:
  model_type: pretrain
  load_pretrained: False #pretrain from scratch
  freeze_vit: True
  path_vit: /path/to/geo-vit-ckpt

datasets:
  geo_caption:
    vis_processor:
        train:
          name: "geometry_image"
          image_size: 224
          # image_size: 448
    text_processor:
        train:
          name: "geometry_caption"
    build_info:
        annotations:
          train:
            storage: data/alignment/train.json
        images:
            storage: data/alignment/images            

run:
  task: formalized_pretraining
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 360
  batch_size_train: 256
  batch_size_eval: 256
  num_workers: 4
  warmup_epoch: 10
  
  seed: 42
  output_dir: "experiments/gsformer_ckpts"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True