- cls_token
- pos_embed
- mask_token
- decoder_pos_embed
- patch_embed.proj.weight
- patch_embed.proj.bias
- blocks.0.norm1.weight
- blocks.0.norm1.bias
- blocks.0.attn.qkv.weight
- blocks.0.attn.qkv.bias
- blocks.0.attn.proj.weight
- blocks.0.attn.proj.bias
- blocks.0.norm2.weight
- blocks.0.norm2.bias
- blocks.0.mlp.fc1.weight
- blocks.0.mlp.fc1.bias
- blocks.0.mlp.fc2.weight
- blocks.0.mlp.fc2.bias
- blocks.1.norm1.weight
- blocks.1.norm1.bias
- blocks.1.attn.qkv.weight
- blocks.1.attn.qkv.bias
- blocks.1.attn.proj.weight
- blocks.1.attn.proj.bias
- blocks.1.norm2.weight
- blocks.1.norm2.bias
- blocks.1.mlp.fc1.weight
- blocks.1.mlp.fc1.bias
- blocks.1.mlp.fc2.weight
- blocks.1.mlp.fc2.bias
- blocks.2.norm1.weight
- blocks.2.norm1.bias
- blocks.2.attn.qkv.weight
- blocks.2.attn.qkv.bias
- blocks.2.attn.proj.weight
- blocks.2.attn.proj.bias
- blocks.2.norm2.weight
- blocks.2.norm2.bias
- blocks.2.mlp.fc1.weight
- blocks.2.mlp.fc1.bias
- blocks.2.mlp.fc2.weight
- blocks.2.mlp.fc2.bias
- blocks.3.norm1.weight
- blocks.3.norm1.bias
- blocks.3.attn.qkv.weight
- blocks.3.attn.qkv.bias
- blocks.3.attn.proj.weight
- blocks.3.attn.proj.bias
- blocks.3.norm2.weight
- blocks.3.norm2.bias
- blocks.3.mlp.fc1.weight
- blocks.3.mlp.fc1.bias
- blocks.3.mlp.fc2.weight
- blocks.3.mlp.fc2.bias
- blocks.4.norm1.weight
- blocks.4.norm1.bias
- blocks.4.attn.qkv.weight
- blocks.4.attn.qkv.bias
- blocks.4.attn.proj.weight
- blocks.4.attn.proj.bias
- blocks.4.norm2.weight
- blocks.4.norm2.bias
- blocks.4.mlp.fc1.weight
- blocks.4.mlp.fc1.bias
- blocks.4.mlp.fc2.weight
- blocks.4.mlp.fc2.bias
- blocks.5.norm1.weight
- blocks.5.norm1.bias
- blocks.5.attn.qkv.weight
- blocks.5.attn.qkv.bias
- blocks.5.attn.proj.weight
- blocks.5.attn.proj.bias
- blocks.5.norm2.weight
- blocks.5.norm2.bias
- blocks.5.mlp.fc1.weight
- blocks.5.mlp.fc1.bias
- blocks.5.mlp.fc2.weight
- blocks.5.mlp.fc2.bias
- blocks.6.norm1.weight
- blocks.6.norm1.bias
- blocks.6.attn.qkv.weight
- blocks.6.attn.qkv.bias
- blocks.6.attn.proj.weight
- blocks.6.attn.proj.bias
- blocks.6.norm2.weight
- blocks.6.norm2.bias
- blocks.6.mlp.fc1.weight
- blocks.6.mlp.fc1.bias
- blocks.6.mlp.fc2.weight
- blocks.6.mlp.fc2.bias
- blocks.7.norm1.weight
- blocks.7.norm1.bias
- blocks.7.attn.qkv.weight
- blocks.7.attn.qkv.bias
- blocks.7.attn.proj.weight
- blocks.7.attn.proj.bias
- blocks.7.norm2.weight
- blocks.7.norm2.bias
- blocks.7.mlp.fc1.weight
- blocks.7.mlp.fc1.bias
- blocks.7.mlp.fc2.weight
- blocks.7.mlp.fc2.bias
- blocks.8.norm1.weight
- blocks.8.norm1.bias
- blocks.8.attn.qkv.weight
- blocks.8.attn.qkv.bias
- blocks.8.attn.proj.weight
- blocks.8.attn.proj.bias
- blocks.8.norm2.weight
- blocks.8.norm2.bias
- blocks.8.mlp.fc1.weight
- blocks.8.mlp.fc1.bias
- blocks.8.mlp.fc2.weight
- blocks.8.mlp.fc2.bias
- blocks.9.norm1.weight
- blocks.9.norm1.bias
- blocks.9.attn.qkv.weight
- blocks.9.attn.qkv.bias
- blocks.9.attn.proj.weight
- blocks.9.attn.proj.bias
- blocks.9.norm2.weight
- blocks.9.norm2.bias
- blocks.9.mlp.fc1.weight
- blocks.9.mlp.fc1.bias
- blocks.9.mlp.fc2.weight
- blocks.9.mlp.fc2.bias
- blocks.10.norm1.weight
- blocks.10.norm1.bias
- blocks.10.attn.qkv.weight
- blocks.10.attn.qkv.bias
- blocks.10.attn.proj.weight
- blocks.10.attn.proj.bias
- blocks.10.norm2.weight
- blocks.10.norm2.bias
- blocks.10.mlp.fc1.weight
- blocks.10.mlp.fc1.bias
- blocks.10.mlp.fc2.weight
- blocks.10.mlp.fc2.bias
- blocks.11.norm1.weight
- blocks.11.norm1.bias
- blocks.11.attn.qkv.weight
- blocks.11.attn.qkv.bias
- blocks.11.attn.proj.weight
- blocks.11.attn.proj.bias
- blocks.11.norm2.weight
- blocks.11.norm2.bias
- blocks.11.mlp.fc1.weight
- blocks.11.mlp.fc1.bias
- blocks.11.mlp.fc2.weight
- blocks.11.mlp.fc2.bias
- norm.weight
- norm.bias
- decoder_embed.weight
- decoder_embed.bias
- decoder_blocks.0.norm1.weight
- decoder_blocks.0.norm1.bias
- decoder_blocks.0.attn.qkv.weight
- decoder_blocks.0.attn.qkv.bias
- decoder_blocks.0.attn.proj.weight
- decoder_blocks.0.attn.proj.bias
- decoder_blocks.0.norm2.weight
- decoder_blocks.0.norm2.bias
- decoder_blocks.0.mlp.fc1.weight
- decoder_blocks.0.mlp.fc1.bias
- decoder_blocks.0.mlp.fc2.weight
- decoder_blocks.0.mlp.fc2.bias
- decoder_blocks.1.norm1.weight
- decoder_blocks.1.norm1.bias
- decoder_blocks.1.attn.qkv.weight
- decoder_blocks.1.attn.qkv.bias
- decoder_blocks.1.attn.proj.weight
- decoder_blocks.1.attn.proj.bias
- decoder_blocks.1.norm2.weight
- decoder_blocks.1.norm2.bias
- decoder_blocks.1.mlp.fc1.weight
- decoder_blocks.1.mlp.fc1.bias
- decoder_blocks.1.mlp.fc2.weight
- decoder_blocks.1.mlp.fc2.bias
- decoder_blocks.2.norm1.weight
- decoder_blocks.2.norm1.bias
- decoder_blocks.2.attn.qkv.weight
- decoder_blocks.2.attn.qkv.bias
- decoder_blocks.2.attn.proj.weight
- decoder_blocks.2.attn.proj.bias
- decoder_blocks.2.norm2.weight
- decoder_blocks.2.norm2.bias
- decoder_blocks.2.mlp.fc1.weight
- decoder_blocks.2.mlp.fc1.bias
- decoder_blocks.2.mlp.fc2.weight
- decoder_blocks.2.mlp.fc2.bias
- decoder_blocks.3.norm1.weight
- decoder_blocks.3.norm1.bias
- decoder_blocks.3.attn.qkv.weight
- decoder_blocks.3.attn.qkv.bias
- decoder_blocks.3.attn.proj.weight
- decoder_blocks.3.attn.proj.bias
- decoder_blocks.3.norm2.weight
- decoder_blocks.3.norm2.bias
- decoder_blocks.3.mlp.fc1.weight
- decoder_blocks.3.mlp.fc1.bias
- decoder_blocks.3.mlp.fc2.weight
- decoder_blocks.3.mlp.fc2.bias
- decoder_blocks.4.norm1.weight
- decoder_blocks.4.norm1.bias
- decoder_blocks.4.attn.qkv.weight
- decoder_blocks.4.attn.qkv.bias
- decoder_blocks.4.attn.proj.weight
- decoder_blocks.4.attn.proj.bias
- decoder_blocks.4.norm2.weight
- decoder_blocks.4.norm2.bias
- decoder_blocks.4.mlp.fc1.weight
- decoder_blocks.4.mlp.fc1.bias
- decoder_blocks.4.mlp.fc2.weight
- decoder_blocks.4.mlp.fc2.bias
- decoder_blocks.5.norm1.weight
- decoder_blocks.5.norm1.bias
- decoder_blocks.5.attn.qkv.weight
- decoder_blocks.5.attn.qkv.bias
- decoder_blocks.5.attn.proj.weight
- decoder_blocks.5.attn.proj.bias
- decoder_blocks.5.norm2.weight
- decoder_blocks.5.norm2.bias
- decoder_blocks.5.mlp.fc1.weight
- decoder_blocks.5.mlp.fc1.bias
- decoder_blocks.5.mlp.fc2.weight
- decoder_blocks.5.mlp.fc2.bias
- decoder_blocks.6.norm1.weight
- decoder_blocks.6.norm1.bias
- decoder_blocks.6.attn.qkv.weight
- decoder_blocks.6.attn.qkv.bias
- decoder_blocks.6.attn.proj.weight
- decoder_blocks.6.attn.proj.bias
- decoder_blocks.6.norm2.weight
- decoder_blocks.6.norm2.bias
- decoder_blocks.6.mlp.fc1.weight
- decoder_blocks.6.mlp.fc1.bias
- decoder_blocks.6.mlp.fc2.weight
- decoder_blocks.6.mlp.fc2.bias
- decoder_blocks.7.norm1.weight
- decoder_blocks.7.norm1.bias
- decoder_blocks.7.attn.qkv.weight
- decoder_blocks.7.attn.qkv.bias
- decoder_blocks.7.attn.proj.weight
- decoder_blocks.7.attn.proj.bias
- decoder_blocks.7.norm2.weight
- decoder_blocks.7.norm2.bias
- decoder_blocks.7.mlp.fc1.weight
- decoder_blocks.7.mlp.fc1.bias
- decoder_blocks.7.mlp.fc2.weight
- decoder_blocks.7.mlp.fc2.bias
- decoder_norm.weight
- decoder_norm.bias
- decoder_pred.weight
- decoder_pred.bias